general_settings/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path("", views.general_info, name="general-settings"),
	path("general_info", views.general_info, name="general-info"),
	path("pf_rates", views.pf_rates, name="pf-rates"),
	path("<int:id>/eeconrib_update/", views.pf_rates_update, name="eecontrib-update"),
	path("<int:id>/eeconrib_delete/", views.pf_rates_delete, name="eecontrib-delete"),
	path("eeconrib_create/", views.pf_rates_create, name="eecontrib-create"),
	path("bank_options", views.bank_options, name="bank-options"),

]

hrms/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('company-show', views.company_show, name='company-show'),
    path('search-company', views.search_company, name='search-company'),
    path('company-update/<int:pk>', views.company_update, name='company-update'),
    path('print-employees/<int:pk>', views.print_employees, name='print-employees'),
    path('company-rates/<int:pk>', views.company_rates, name='company-rates'),
    path('company-gov-deducts/<int:pk>',
         views.company_gov_deducts, name='company-gov-deducts'),
    path('company-other-options/<int:pk>',
         views.company_other_options, name='company-other-options'),
    path('company-add', views.company_add, name='company-add'),
    path('company-delete/<int:pk>', views.company_delete, name='company-delete')
]

payroll/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [path('', include('hrms.urls')),
               path('general_settings/', include('general_settings.urls')),
               path('login/', include('login.urls')),
               path('logs/', include('logs.urls')),
               path('employees/', include('employee.urls')),
               path('admin/', admin.site.urls),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

general_settings/models.py
from django.db import models

# Create your models here.


class General_settings(models.Model):
    main_company = models.CharField(default="company", max_length=255)
    template_name = models.CharField(default="Company Inc.", max_length=255)
    company_address = models.CharField(default="Company Location", max_length=255)
    company_contacts = models.CharField(default="02 xxx-xxxx / 02 xxx-xxxx", max_length=255)

    def __str__(self):
        return f'{self.main_company}'


class BracketSSContribEE(models.Model):
    contrib_amount = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    ranged = models.CharField(max_length=100)

employee/forms.py
from django import forms
from .models import Employee, Employee_preferences, Employment_record, Employee_hiring_details, Employee_resume, Employee_company_loan, Employee_uniform, Employee_medical, Employee_canteen, Employee_gatepass, Employee_vale, Employee_pagibig_loan,  Employee_acceptance, Employee_leave_history, Employee_citizenship, Employee_picture, Employee_requirements, Employee_memo
from hrms.models import Company
from general_settings.models import BracketSSContribEE


class EmployeeAddForm(forms.ModelForm):
	date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))
	GENDER = CHOICES = (('', 'Choose gender'),('male', 'Male'), ('female', 'Female'))
	gender = forms.CharField(widget=forms.Select(choices=GENDER))

	def __init__(self, *args, **kwargs):
		super(EmployeeAddForm, self).__init__(*args, **kwargs)
		queryset = Employee_citizenship.objects.values_list('citizenship', flat=True).distinct()
		self.fields['middle_name'].required = False

		CITIZENSHIP = [('', 'Choose citizenship'), ('indian', 'Indian')] + [(citizenship, citizenship) for citizenship in queryset]
		self.fields['citizenship'] = forms.ChoiceField(choices=CITIZENSHIP,  widget=forms.Select(attrs={'onchange': 'Hide()'}))

	CIVIL_STATUS = CHOICES = (('', 'Choose status'),('single', 'Single'), ('married', 'Married'))
	civil_status = forms.CharField(widget=forms.Select(choices=CIVIL_STATUS))
	date_hired = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))
	contract_expiration = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))

	SSS_OPTION = CHOICES = (('0', 'Choose Sss Option'),
							('bracket', 'By Range'),
							('manual', 'By manual'),)
	sss_option = forms.CharField(label='PF option', widget=forms.Select(choices=SSS_OPTION, attrs={'onchange': 'HideSSS()'}))

	USE_COM = CHOICES = (
		('', 'Choose Gov Deduction to Implement'),
		('company_base_deductions', 'Company Base Deductions'),
	)
	gov_deductions_to_implement = forms.CharField(
		widget=forms.Select(choices=USE_COM, attrs={'onchange': 'HideGovDeductions()'}))

	brackets_queryset = BracketSSContribEE.objects.all()
	SSS_BRACKET = [('0', 'Choose Bracket')] + [(brackets.contrib_amount, brackets.ranged) for brackets in
											   brackets_queryset]
	sss_bracket = forms.CharField(label='PF Range', widget=forms.Select(choices=SSS_BRACKET))
	philhealth_value = forms.DecimalField(label='Health value')

	sss_no = forms.CharField(label='PF no.', widget=forms.TextInput(attrs={'type': 'number'}), )
	pagibig_no = forms.CharField(label='ESI no.', widget=forms.TextInput(attrs={'type': 'number'}), )
	philhealth_no = forms.CharField(label='Health insurance id', widget=forms.TextInput(attrs={'type': 'number'}), )
	tin_no = forms.CharField(label='Aadhaar No.', widget=forms.TextInput(attrs={'type': 'number'}),)

	class Meta:
		model = Employee
		fields = ['first_name', 'middle_name', 'last_name', 'emp_id', 'address', 'provincial_address', 'date_of_birth', 'date_hired', 'contract_expiration', 'gender', 'place_of_birth', 'civil_status', 'phone', 'company', 'gov_deductions_to_implement', 'sss_no', 'pagibig_no', 'sss_option', 'sss_bracket', 'sss_value', 'pagibig_value', 'philhealth_value', 'philhealth_no', 'tin_no', 'citizenship', 'remarks']
		


class PreferencesForm(forms.ModelForm):
	character_reference_name = forms.CharField(label='Nominee Name')
	character_reference_address = forms.CharField(label='Nominee Address')
	character_reference_phone = forms.CharField(label='Nominee Phone No.')

	class Meta:
		model = Employee_preferences
		exclude = ['employee']


class RecordsForm(forms.ModelForm):
	from_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))
	to_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))

	class Meta:
		model = Employment_record
		exclude = ['employee']


class HiringDetailsForm(forms.ModelForm):
	PAYMENT_METHOD_CHOICES = CHOICES = (('', 'Choose method'),('weekly', 'Weekly'), ('semi-monthly', 'Semi-monthly'), ('monthly', 'Monthly'))
	payment_method = forms.CharField(widget=forms.Select(choices=PAYMENT_METHOD_CHOICES))
	BANK_CHOICES = CHOICES = (('', 'Choose bank'), ('ICICI', 'ICICI'), ('SBI', 'SBI'), ('HDFC', 'HDFC'),
							  ('axis', 'Axis'), ('Canara', 'Canara'), ('KVB', 'KVB'), ('others', 'others'),)
	bank = forms.CharField(label='Bank Name', widget=forms.Select(choices=BANK_CHOICES))
	rate = forms.DecimalField(label='Regular Pay')
	atm = forms.CharField(label='Account No.')
	overtime_formula = forms.CharField(label="Input overtime multiplier. (ex. 1.25)")

	class Meta:
		model = Employee_hiring_details
		exclude = ['employee']


class ResumeForm(forms.ModelForm):
	resume = forms.FileField(label='', help_text='')
	class Meta:
		model = Employee_resume
		exclude = ['employee']


class PictureForm(forms.ModelForm):
	picture = forms.FileField(label='', help_text='')

	class Meta:
		model = Employee_picture
		exclude = ['employee']


class CompanyLoanForm(forms.ModelForm):
	status = CHOICES = (('', 'Choose status'), ('Paid', 'Paid'), ('Not yet paid', 'Not Yet Paid'))
	status = forms.BooleanField(label="Paid", required=False)
	load_amount = forms.CharField(label="Loan Amount")
	class Meta:
		model = Employee_company_loan
		exclude = ['employee']


class PagibigLoanForm(forms.ModelForm):
	status = CHOICES = (('', 'Choose status'), ('Paid', 'Paid'), ('Not yet paid', 'Not Yet Paid'))
	status = forms.BooleanField(label="Paid", required=False)
	class Meta:
		model = Employee_pagibig_loan
		exclude = ['employee']


class UniformForm(forms.ModelForm):
	status = CHOICES = (('', 'Choose status'), ('Used', 'Used'), ('Not Used', 'Not Used'))
	status = forms.BooleanField(label="Used", required=False)
	class Meta:
		model = Employee_uniform
		exclude = ['employee']


class MedicalForm(forms.ModelForm):
	status = CHOICES = (('', 'Choose status'), ('Paid', 'Paid'), ('Not yet paid', 'Not Yet Paid'))
	status = forms.BooleanField(label="Paid", required=False)
	class Meta:
		exclude = ['employee']
		model = Employee_medical


class CanteenForm(forms.ModelForm):
	status = CHOICES = (('', 'Choose status'), ('Used', 'Used'), ('Not Used', 'Not Used'))
	status = forms.BooleanField(label="Used", required=False)

	class Meta:
		model = Employee_canteen
		exclude = ['employee']


class GatepassForm(forms.ModelForm):
	status = CHOICES = (('', 'Choose status'), ('Used', 'Used'), ('Not Used', 'Not Used'))
	status = forms.BooleanField(label="Used", required=False)
	class Meta:
		model = Employee_gatepass
		exclude = ['employee']


class ValeForm(forms.ModelForm):
	status = CHOICES = (('', 'Choose status'), ('Paid', 'Paid'), ('Not yet paid', 'Not Yet Paid'))
	status = forms.BooleanField(label="Paid", required=False)
	class Meta:
		model = Employee_vale
		exclude = ['employee']


class SearchForm(forms.ModelForm):
	company_name = forms.CharField(label='',
								   widget= forms.TextInput(attrs={'placeholder':'Company'}), required=False)

	class Meta:
		model = Company
		fields = ['company_name']


class EmployeeAcceptanceForm(forms.ModelForm):
	employment_status = CHOICES = (('', 'Choose status'),('Casual / Probationary', 'Casual / Probationary'), ('Seasonal', 'Seasonal'), ('Regular', 'Regular'))
	employment_status = forms.CharField(widget=forms.Select(choices=employment_status))
	start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))
	end_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))
	class Meta:
		model = Employee_acceptance
		fields = ['employment_status', 'start_date', 'end_date', 'position', 'salary_per_day', 'salary_per_month']


class EmployeeLeaveHistory(forms.ModelForm):
	start_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))
	end_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))
	class Meta:
		model = Employee_leave_history
		fields = ['start_date', 'end_date', 'no_of_days']


class UpdateRecord(forms.ModelForm):
	from_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))
	to_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker'}))
	company = forms.CharField(label='Company Name')

	class Meta:
		model = Employment_record
		exclude = ['employee']


class Requirements(forms.ModelForm):
	nbi = forms.BooleanField(label="Pan Copy")
	barangay = forms.BooleanField(label="Aadhaar Card")
	medical = forms.BooleanField(label="Medical Report")
	sss_id = forms.BooleanField(label="PF Id")
	pagibig_id = forms.BooleanField(label="ESI Id")
	birth_certificate = forms.BooleanField(label="Birth Certificate")
	atm_application = forms.BooleanField(label="ATM Application Details")
	ph_id = forms.BooleanField(label="Health Insurance Id")
	hs_diploma = forms.BooleanField(label="Higher Secondary Certificate")
	college_diploma = forms.BooleanField(label="College Certificate")
	employee_contract = forms.BooleanField(label="Employee Contract")
	certificate_of_employment = forms.BooleanField(label="Certificate of Employment")
	photo = forms.BooleanField(label="Passport Size Photo")

	def __init__(self, *args, **kwargs):
		super(Requirements, self).__init__(*args, **kwargs)
		self.fields['nbi'].required = False
		self.fields['barangay'].required = False
		self.fields['medical'].required = False
		self.fields['sss_id'].required = False
		self.fields['pagibig_id'].required = False
		self.fields['birth_certificate'].required = False
		self.fields['atm_application'].required = False
		self.fields['ph_id'].required = False
		self.fields['hs_diploma'].required = False
		self.fields['college_diploma'].required = False
		self.fields['employee_contract'].required = False
		self.fields['certificate_of_employment'].required = False
		self.fields['photo'].required = False
		

	class Meta:
		model = Employee_requirements
		exclude = ['employee']


class MemoForm(forms.ModelForm):
	class Meta:
		model = Employee_memo
		exclude = ['employee']

general_settings/forms.py
from django import forms
from .models import General_settings, BracketSSContribEE

class GeneralInfoForm(forms.ModelForm):
	class Meta:
		model = General_settings
		fields = ['main_company', 'template_name', 'company_address', 'company_contacts']


class BracketSSContribEEForm(forms.ModelForm):
	contrib_amount = forms.DecimalField(label="Contribution Amount")
	ranged = forms.CharField(label="Salary Ranged")

	class Meta:
		model = BracketSSContribEE
		fields = ['contrib_amount', 'ranged']

general_settings/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from .models import General_settings, BracketSSContribEE
from .forms import GeneralInfoForm, BracketSSContribEEForm
from django.contrib import messages


def general_info(request):
    data = get_object_or_404(General_settings, pk=1)
    form = GeneralInfoForm(request.POST or None, instance=data)

    if form.is_valid():
        form.save()
        messages.success(request, "Company info was successfully updated.")
        request.session['main_company'] = data.main_company
        return redirect('general-info')

    context = {
        'title': 'VS Payroll Management',
        "page_nick": 'general-info',
        "head": "General Settings",
        "form": form,
        "main_company": data
    }
    return render(request, "gs_home.html", context)


def pf_rates(request):
    ee_pf_contrib = BracketSSContribEE.objects.all()

    context = {
        'title': 'VS Payroll Management',
        "page_nick": "pf-rates",
        "head": "Employee PF Contribution",
        "ee_pf_contrib": ee_pf_contrib
    }
    return render(request, "gs_eecontribss.html", context)


def pf_rates_create(request):
    form = BracketSSContribEEForm(request.POST or None)

    if form.is_valid():
        form.save()
        form = BracketSSContribEEForm()
        return redirect('pf-rates')

    context = {
        'title': 'VS Payroll Management System',
        'page_nick': 'pf-rates',
        'form': form
    }
    return render(request, 'gs_home.html', context)


def pf_rates_delete(request, id):
    obj = get_object_or_404(BracketSSContribEE, id=id)
    obj.delete()
    return redirect('pf-rates')


def pf_rates_update(request, id):
    obj = get_object_or_404(BracketSSContribEE, id=id)
    form = BracketSSContribEEForm(request.POST or None, instance=obj)

    if form.is_valid():
        form.save()
        return redirect('pf-rates')

    context = {
        'title': 'VS Payroll Management System',
        'page_nick': 'pf-rates',
        'form': form
    }
    return render(request, 'gs_home.html', context)


def bank_options(request):
    return HttpResponse('bank options')

general_settings/templates/gs_eecontribss.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="card">
		<div class="card-header">
            <h4 class="card-title">
            {{ head }}
            </h4>
        </div>
		<div class="card-body">
			<a href="{% url 'general-info' %}" class="btn btn-{% if page_nick == 'general-info'%}primary{% else %}danger{% endif %}">Company Info</a>
			<a href="{% url 'pf-rates' %}" class="btn btn-{% if page_nick == 'pf-rates'%}success{% else %}success{% endif %}">PF Rates</a>
		</div>
</div>
<div class="card">
	<div class="card-body">

		<div class="card-body">

        <a href='{% url "eecontrib-create" %}' class="btn btn-primary" >Create New</a>

				{% comment %} <form class="form-control" action="{% url 'search-employees' %}" method="post" style="margin-top: 10px">
						{% csrf_token %}
					<div class="row">
	            <div class="col example-grid-col">
								  <select class="form-control" name="company">
								  	<option value="">Choose company</option>
										{% for com in companies %}
											<option value="{{com.company_name}}">{{com.company_name}}</option>
										{% endfor %}
								  </select>
	            </div>
	            <div class="col example-grid-col">
	                <input type="text" class="form-control" name="employee_name" value="" placeholder="Search by employee">
	            </div>

				<div class="col example-grid-col">
					<select class="form-control" name="payment_method">
						<option value="">Choose payment method</option>
							<option value="daily">daily</option>
							<option value="weekly">weekly</option>
							<option value="semi-monthly">semi-monthly</option>
							<option value="monthly">monthly</option>
					</select>
	            </div>

	            <div class="col example-grid-col">
	                <input type="text" name="start_date" value="" class="datepicker dateinput form-control"  id="id_date_hired" placeholder="Start Date">
	            </div>
	            <div class="col example-grid-col">
	                <input type="text" name="end_date" value="" class="datepicker dateinput form-control"  id="id_date_hired" placeholder="End Date">
	            </div>

	            <div class="col example-grid-col">
					<select class="form-control" name="search_by">
						<option value="">Choose Search By</option>
							<option value="date_hired">Date Hired</option>
							<option value="contract_expiration">Contract Expiration</option>
					</select>
	            </div>

	            <div class="col example-grid-col">
					<select class="form-control" name="order">
						<option value="">Choose Order</option>
							<option value="ascending">ascending</option>
							<option value="descending">descending</option>
					</select>
	            </div>

							<div class="col example-grid-col">
	                <button type="submit" class="btn btn-info" name="button">Search</button>
	            </div>
	        </div>
				</form> {% endcomment %}
				<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
			<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

			<div class="table-responsive" style="margin-top: 10px">
				<table id="example" class="table table-striped table-bordered" style="width:100%">

					<thead style="background-color: #539394; color:white;">
						<tr>
							<th scope="col" class="text-center">S.No</th>
							<th scope="col" class="text-center">Contribution Amount</th>
							<th scope="col" class="text-center">Salary Ranged</th>
							<th scope="col" class="text-center">Action</th>
						</tr>
					</thead>
					<tbody>
						{% for ee_contrib in ee_pf_contrib %}
							<tr>
								<th class="align-middle text-center" scope="row">{{ forloop.counter}}</th>
								<td class="align-middle text-center">{{ ee_contrib.contrib_amount }} </td>
								<td class="align-middle text-center">{{ ee_contrib.ranged }} </td>
								<td class="align-middle text-center">
									<a href="{% url 'eecontrib-update' ee_contrib.id %}" class="btn btn-primary">Update</a>
									<a href="{% url 'eecontrib-delete' ee_contrib.id %}" onclick="return confirm('Are you sure you want to delete this contribution?');" class="btn btn-danger">Delete</a>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

general_settings/templates/gs_home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="card">
		<div class="card-header">
            <h4 class="card-title">
            {{ head }}
            </h4>
        </div>
		<div class="card-body">
			<a href="{% url 'general-info' %}" class="btn btn-{% if page_nick == 'general-info'%}danger{% else %}warning{% endif %}">Company Info</a>
			<a href="{% url 'pf-rates' %}" class="btn btn-{% if page_nick == 'pf-rates'%}success{% else %}success{% endif %}">PF Rates</a>
		</div>
</div>

<div class="card">
	<div class="card-body">

		{% if page_nick == 'pf-rates' %}
		<h3>Create New PF Rates</h3><br>
		<div class="pull-left">
		    <a href="{% url 'pf-rates' %}" class="btn btn-info">Go Back</a>
		</div>
		{% endif %}
		

		<div class="row">
			<div class="col example-grid-col">
			</div>
			<div class="col-7 example-grid-col">
				<form method="POST" novalidate="">
					<div class="form-group">
						{% csrf_token %}
						{{ form|crispy  }}
					</div>
					<button type="submit" class="btn btn-success"> Save</button>
				</form>
			</div>
			<div class="col example-grid-col">
			</div>
		</div>
	</div>
</div>

	
{% endblock content %}